# Generated by Django 2.2.4 on 2019-09-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='added',
            new_name='date_added_db',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='date_posted',
        ),
    ]
