# Generated by Django 2.2.4 on 2019-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190901_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
