# Generated by Django 2.2.4 on 2019-09-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190901_2118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('company', 'title')},
        ),
    ]
