# Generated by Django 2.2.4 on 2019-09-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190901_2142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('company', 'title', 'date_posted')},
        ),
    ]
