# Generated by Django 2.2.4 on 2019-09-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190901_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('company', 'title', 'date_posted')},
        ),
    ]
