# Generated by Django 2.2.5 on 2019-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20190911_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Full Stack Engineer', 'Full Stack Engineer'), ('Front End Engineer', 'Front End Engineer'), ('Back End Engineer', 'Back End Engineer')], max_length=255),
        ),
    ]
